title: Mohd Tanveer Shaikh # your name (or website title) here
logo: "/b05511ee-3c57-42e7-8a11-0df3105557e2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer
  <br><br>
  <a href="mailto:mohdtanveersh@gmail.com">mohdtanveersh@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/tanveer-/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/mohd-tanveer/">Gihub</a> 
theme: jekyll-theme-minimal
